version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    pid: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      # - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  # restic:
  #   image: mazzolino/restic:1.7
  #   hostname: restic
  #   user: "root:root" # To allow restic read files even with restrictive permissions set
  #   restart: unless-stopped
  #   environment:
  #     RUN_ON_STARTUP: "true"
  #     BACKUP_CRON: "0 30 3 * * *"
  #     RESTIC_BACKUP_SOURCES: /mnt/source
  #     RESTIC_BACKUP_ARGS: >-
  #       --tag surek-volumes
  #       --verbose
  #     RESTIC_FORGET_ARGS: >-
  #       --keep-last 10
  #       --keep-daily 7
  #       --keep-weekly 5
  #       --keep-monthly 12
  #   volumes:
  #     - ../surek-data/volumes:/mnt/source:ro
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  
  # restic_prune:
  #   image: mazzolino/restic:1.7
  #   hostname: restic
  #   restart: unless-stopped
  #   environment:
  #     SKIP_INIT: "true"
  #     RUN_ON_STARTUP: "true"
  #     PRUNE_CRON: "0 0 4 * * *"
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro

  # restic_check:
  #   image: mazzolino/restic:1.7
  #   hostname: restic
  #   restart: unless-stopped
  #   environment:
  #     SKIP_INIT: "true"
  #     RUN_ON_STARTUP: "false"
  #     CHECK_CRON: "0 15 5 * * *"
  #     RESTIC_CHECK_ARGS: >-
  #       --read-data-subset=10%
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro

  whoami:
    image: traefik/whoami
    

volumes:
  caddy_data: {}
  portainer_data: {}
  netdata_config: {}
  netdata_lib: {}
  netdata_cache: {}