version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    pid: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      # - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  backup:
    image: offen/docker-volume-backup:latest
    restart: unless-stopped
    volumes:
      - ../../volumes:/backup:ro
      - ./backup-daily.env:/etc/dockervolumebackup/conf.d/backup-daily.env
      - ./backup-weekly.env:/etc/dockervolumebackup/conf.d/backup-weekly.env
      - ./backup-monthly.env:/etc/dockervolumebackup/conf.d/backup-monthly.env
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    

volumes:
  caddy_data: {}
  portainer_data: {}
  netdata_config: {}
  netdata_lib: {}
  netdata_cache: {}